spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      enabled: true # ???? ??? ???? (default: true)
      file-size-threshold: 0B # ??? ???? ???? ?? ???? ???? ?? ?? (default: 0B)
      # ??? ?? ??(??? ?? ?? ?)? ?? ??? ????? ??? ?? ?? ?? ??
      location: /users/charming/temp # ???? ??? ??? ???? ??? ?? (default: WAS? ??)
      max-file-size: 100MB # ?? ??? ?? ??? (default: 1MB)
      max-request-size: 100MB # ?? ??? ?? ??? (default: 10MB)