spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      # 임시 디렉터리에 저장된 파일은 힙 메모리가 아닌 Servlet Container Disk에 저장됨
      # 즉, file-size-threshold 초과한 크기의 파일 모두 아래 경로에 임시 저장
      # 업로드 중간에 실패하는 등 장애 발생 시 명시적으로 임시 파일 삭제를 위해 경로 지정 필요
      # 가끔 임시 파일 삭제되지 않고 남아있는 경우 별도 삭제 작업 필요한데 이를 용이하게 하기 위해 지정
      location: /users/parkcheorhyeon/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)